
export const IMG = {
  watchWhite: "1523275335684-37898b6baf30",
  headphonesYellow: "1505740420928-5e560c06d30e",
  instantCamera: "1526170375885-4d8ecf77b99f",
  sunglasses: "1572635196237-14b3f281503f",
  sneakerGrey: "1491553895911-0055eca6402d",
  shoeGreen: "1560343090-f0409e92791a",
  smartwatch: "1546868871-7041f2a55e12",
  headphonesGrey: "1583394838336-acd977736f90",
  speakerBlack: "1608043152269-423dbba4e7e1",
  sneakerWhiteOrange: "1600185365483-26d7a4cc7519",
  backpackNavy: "1553062407-98eeb64c6a62",
  handbagRed: "1584917865442-de89df76afd3",
  handbagWoven: "1590874103328-eac38a683ce7",
  handbagTeal: "1594223274512-ad4803739b7c",
  mugWhite: "1514228742587-6b1558fcca3d",
  cupsStoneware: "1610701596007-11502861dcfa",
  platesBlue: "1578749556568-bc2c40e68b61",
  candleFur1: "1602874801007-bd458bb1b8b6",
  candleFur2: "1603006905003-be475563bc59",
  skincareTube: "1556228578-8c89e6adf883",
  creamTube: "1620916566398-39f1143ab7be",
  purpleBottles: "1571781926291-c477ebfd024b",
  skincareSet: "1608248597279-f99d160bfcbc",
  skincareFlatlay: "1598440947619-2c35fc9aa908",
  latteArt: "1495474472287-4d71bcdd2085",
  coffeeBeans: "1447933601403-0c6688de566e",
  coffeeBag: "1559056199-641a0ac8b55e",
  lattes: "1509042239860-f550ce710b93",
  succulentTeal: "1485955900006-10f4d324d411",
  cactusPink: "1459411552884-841db9b3cc2a",
  plantSprig: "1501004318641-b39e6451bec6",
  cactusField: "1463936575829-25148e1db1b8",
  clothesRack: "1512436991641-6745cdb1723f",
  teeWhite: "1521572163474-6864f9cf17ab",
  leatherJacket: "1551028719-00167b16eac5",
  bomberRust: "1591047139829-d91aecb6caea",
  knitPoncho: "1434389677669-e08b4cac3105",
  yellowSet: "1515886657613-9f3515b0c78f",
  rackNeutral: "1490481651871-ab68de25d43d",
  sofaGreen: "1555041469-a586c61ea9bc",
  roomYellowChair: "1586023492125-27b2c045efd7",
  chairWhite: "1567538096630-e0c55bd6374c",
  officeLounge: "1524758631624-e2822e304c36",
  lampGrey: "1507473885765-e6ed057f782c",
  pendantTeal: "1513506003901-1e6a229e2d15",
  toteKraft: "1544816155-12df9643f363",
  notebookPen: "1517842645767-c639042777db",
  penBlack: "1583485088034-697b5bc54ccd",
  pearls: "1515562141207-7a88fb7ce338",
  pendantNecklace: "1599643478518-a784e5dc4c8f",
  ringDiamond: "1605100804763-247f67b3557e",
  braceletRose: "1611591437281-460bfbe1220a",
  earringsBlue: "1535632066927-ab7c9ab60908",
  goldRings: "1617038220319-276d3cfab638",
  backpackRed: "1622560480605-d83c853bc5c3",
  yoga: "1544367567-0f2fcb009e0b",
  tentView: "1504280390367-361c6d9f38f4",
  campfire: "1478131143081-80f7f84ca84d",
  shirtsSage: "1523381210434-271e8be1f52b",
  knitFlatlay: "1556905055-8f358a7a47b2",
  teeBlack: "1618354691373-d851c5c3a990",
  jeans: "1542272604-787c3835535d",
  chinos: "1473966968600-fa801b869a1a",
  sneakerMaroon: "1525966222134-fcfa99b8ae77",
  sneakerVolt: "1606107557195-0e29a4b5b4aa",
  sneakerPastel: "1595950653106-6c9ebd614d3a",
  controller: "1600080972464-8e5f35f63d08",
  headphonesChrome: "1484704849700-f032a568e944",
  headphonesBeige: "1545127398-14699f92334b",
  laptopDesk: "1496181133206-80ce9b88a853",
  keyboardWhite: "1587829741301-dc798b83add3",
  keyboardMech: "1618384887929-16ec33fab9ef",
  mouseWhite: "1527814050087-3793815479db",
  cameraDark: "1516035069371-29a1b244cc32",
  cameraCanon: "1502920917128-1aa500764cbd",
  earbuds: "1590658268037-6bf12165a8df",
  teaCookies: "1544787219-7f47ccb76574",
  icedTea: "1556679343-c7306c1976bc",
  espresso: "1610889556528-9a770e32642f",
  kitchen: "1556911220-bff31c812dba",
  knives: "1593618998160-e34014e67546",
  monstera: "1614594975525-e45190c55d0b",
  aloe: "1509423350716-97f9360b4e09",
  trowel: "1416879595882-3373a0480b5b",
  manTee: "1622445275463-afa2ab738c34",
  wallet: "1627123424574-724758594e93",
  throws: "1600369672770-985fd30004eb",
  candlesAmber: "1572726729207-a78d6feb18d7",
  makeupBrushes: "1596462502278-27bfdc403348",
  pumpBottles: "1631729371254-42c2892f0e6e",
  apothecary: "1612817288484-6f916006741a",
  soapBars: "1600857544200-b2f666a9a2ec",
  storeInterior: "1441986300917-64674bd600d8",
  shopCounter: "1556740738-b6a63e27c4df",
  shoppingBag: "1534452203293-494d7ddbf7e0",
  boutiqueRacks: "1567401893414-76b7b1e5a7a5",
  craftTools: "1452860606245-08befc0ff44b",
  potteryHands: "1493106641515-6b5631de4bb9",
  oilDropper: "1617897903246-719242758050",
  serumBottles: "1611930022073-b7a4ba5fcccd",
  creamJar: "1619451334792-150fd785ee74",
  bottleGreen: "1602143407151-7111542de6e8",
  greenRoom: "1600494603989-9650cf6ddd3d",
  necklaceModel: "1611652022419-a9419f74343d",
  amberDropper: "1608571423902-eed4a5ad8108",
  vases: "1631125915902-d8abe9225ff2",
  livingRoom: "1616486338812-3dadae4b4ace",
  loungeOrange: "1618220179428-22790b461013",
  copperPendants: "1540932239986-30128078f3c5",
  wallClock: "1533090161767-e6ffed986c88",
  eamesStool: "1581539250439-c96689b516dd",
  chairBlack: "1592078615290-033ee584e267",
  stoolWood: "1503602642458-232111445657",
  diningNook: "1519710164239-da123dc03ef4",
  chairSpot: "1549497538-303791108f95",
} as const;

export const AVATARS = {
  w1: "1494790108377-be9c29b29330",
  m1: "1507003211169-0a1dd7228f2d",
  m2: "1500648767791-00dcc994a43e",
  w2: "1438761681033-6461ffad8d80",
  m3: "1472099645785-5658abf4ff4e",
  w3: "1534528741775-53994a69daeb",
  w4: "1544005313-94ddf0286df2",
  m4: "1506794778202-cad84cf45f1d",
  w5: "1531746020798-e6953c6e8e04",
} as const;

type ImgKey = keyof typeof IMG;

export type CategorySeed = {
  slug: string;
  name: string;
  description: string;
  image: ImgKey;
  children: { slug: string; name: string; image: ImgKey }[];
};

export const CATEGORIES: CategorySeed[] = [
  {
    slug: "home-living",
    name: "Home & Living",
    description: "Handmade ceramics, candles and objects from studios across India.",
    image: "cupsStoneware",
    children: [
      { slug: "ceramics-tableware", name: "Ceramics & Tableware", image: "platesBlue" },
      { slug: "candles-fragrance", name: "Candles & Fragrance", image: "candleFur1" },
      { slug: "decor", name: "Decor & Textiles", image: "vases" },
      { slug: "stationery", name: "Stationery", image: "notebookPen" },
    ],
  },
  {
    slug: "furniture-lighting",
    name: "Furniture & Lighting",
    description: "Solid-wood furniture and lighting from Indian workshops — built to be kept.",
    image: "livingRoom",
    children: [
      { slug: "seating", name: "Seating", image: "roomYellowChair" },
      { slug: "lighting", name: "Lighting", image: "copperPendants" },
    ],
  },
  {
    slug: "fashion",
    name: "Fashion",
    description: "Everyday staples in khadi, linen and organic cotton from small-batch labels.",
    image: "rackNeutral",
    children: [
      { slug: "tops", name: "Tops & Tees", image: "teeWhite" },
      { slug: "outerwear", name: "Outerwear", image: "leatherJacket" },
      { slug: "bottoms", name: "Bottoms", image: "jeans" },
      { slug: "knitwear-lounge", name: "Knitwear & Lounge", image: "knitPoncho" },
    ],
  },
  {
    slug: "footwear",
    name: "Footwear",
    description: "Sneakers and everyday shoes, from the running track to the street.",
    image: "sneakerPastel",
    children: [
      { slug: "sneakers", name: "Sneakers", image: "sneakerGrey" },
      { slug: "casual-shoes", name: "Casual Shoes", image: "shoeGreen" },
    ],
  },
  {
    slug: "bags-accessories",
    name: "Bags & Accessories",
    description: "Leather goods from Kanpur, carry-alls and the finishing touches.",
    image: "handbagWoven",
    children: [
      { slug: "handbags", name: "Handbags", image: "handbagRed" },
      { slug: "backpacks", name: "Backpacks", image: "backpackNavy" },
      { slug: "small-leather-goods", name: "Small Leather Goods", image: "wallet" },
      { slug: "eyewear", name: "Eyewear", image: "sunglasses" },
    ],
  },
  {
    slug: "jewelry",
    name: "Jewellery",
    description: "Fine and demi-fine pieces from Jaipur and Hyderabad, made for everyday wear.",
    image: "goldRings",
    children: [
      { slug: "necklaces", name: "Necklaces", image: "pendantNecklace" },
      { slug: "rings", name: "Rings", image: "ringDiamond" },
      { slug: "earrings-bracelets", name: "Earrings & Bracelets", image: "braceletRose" },
    ],
  },
  {
    slug: "beauty",
    name: "Beauty & Wellness",
    description: "Ayurvedic skincare, bath rituals and tools from indie formulators.",
    image: "skincareFlatlay",
    children: [
      { slug: "skincare", name: "Skincare", image: "skincareSet" },
      { slug: "bath-body", name: "Bath & Body", image: "soapBars" },
      { slug: "makeup-tools", name: "Makeup & Tools", image: "makeupBrushes" },
    ],
  },
  {
    slug: "tech",
    name: "Tech & Audio",
    description: "Headphones, cameras and desk gear, tuned and tested in Bengaluru.",
    image: "headphonesBeige",
    children: [
      { slug: "audio", name: "Audio", image: "headphonesYellow" },
      { slug: "wearables", name: "Wearables", image: "smartwatch" },
      { slug: "cameras", name: "Cameras", image: "cameraCanon" },
      { slug: "desk-setup", name: "Desk Setup", image: "keyboardMech" },
    ],
  },
  {
    slug: "coffee-kitchen",
    name: "Coffee & Kitchen",
    description: "Estate coffee from Chikkamagaluru, chai blends and the tools to brew them.",
    image: "latteArt",
    children: [
      { slug: "coffee-tea", name: "Coffee & Tea", image: "coffeeBag" },
      { slug: "kitchen-tools", name: "Kitchen Tools", image: "knives" },
    ],
  },
  {
    slug: "plants-outdoor",
    name: "Plants & Outdoor",
    description: "Houseplants, garden tools and gear for the Himalayas and beyond.",
    image: "monstera",
    children: [
      { slug: "houseplants", name: "Houseplants", image: "succulentTeal" },
      { slug: "garden", name: "Garden", image: "trowel" },
      { slug: "outdoor-gear", name: "Outdoor Gear", image: "tentView" },
    ],
  },
];

export type ProductSeed = {
  title: string;
  category: string;
  price: number;
  compareAt?: number;
  images: ImgKey[];
  summary: string;
  options?: { name: string; values: string[] }[];
  priceMods?: Record<string, number>;
  specs?: [string, string][];
  tags?: string[];
  featured?: boolean;
};

export type StoreSeed = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  owner: { name: string; email: string; avatar?: keyof typeof AVATARS };
  category: string;
  location: string;
  brandColor: string;
  banner: ImgKey;
  logo: ImgKey;
  featured?: boolean;
  verified?: boolean;
  policies: { shipping: string; returns: string; processingTime: string };
  products: ProductSeed[];
};

const SIZES_APPAREL = ["XS", "S", "M", "L", "XL"];
const SIZES_SHOES = ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"];

export const STORES: StoreSeed[] = [
  {
    slug: "mitti-studio",
    name: "Mitti Studio",
    tagline: "Small-batch stoneware and hand-poured candles from Pondicherry.",
    description:
      "Mitti Studio is a two-person pottery studio just outside Pondicherry, a short walk from the sea. Every mug, plate and vase is thrown on the wheel, trimmed by hand and fired in our gas kiln — so no two pieces are quite the same. Our candles are poured in the same studio from soy wax and natural attars like sandalwood, mogra and vetiver.\n\nWe started at the Sunday market on Goubert Avenue in 2019 and still pack every order ourselves.",
    owner: { name: "Priya Raman", email: "vendor@vanik.dev", avatar: "w3" },
    category: "home-living",
    location: "Puducherry",
    brandColor: "#a8461f",
    banner: "potteryHands",
    logo: "cupsStoneware",
    featured: true,
    verified: true,
    policies: {
      processingTime: "Ships in 2–4 working days",
      shipping:
        "Every piece is double-boxed with paper padding and shipped via Delhivery. Free standard shipping on orders above ₹999 anywhere in India. Express delivery with Blue Dart is available at checkout.",
      returns:
        "Unused items can be returned within 7 days for a full refund. If anything arrives damaged, send us an unboxing photo within 48 hours and we’ll replace it free of charge.",
    },
    products: [
      {
        title: "Everyday Stoneware Mug",
        category: "ceramics-tableware",
        price: 899,
        images: ["mugWhite", "cupsStoneware", "kitchen"],
        summary: "A 350 ml wheel-thrown mug with a generous handle and a satin glaze that feels good in the hand — made for your morning filter coffee or chai.",
        options: [{ name: "Color", values: ["Chalk", "Oat", "Charcoal"] }],
        specs: [["Capacity", "350 ml"], ["Material", "Mid-fire stoneware"], ["Care", "Dishwasher & microwave safe"], ["Dimensions", "9 cm W × 10 cm H"]],
        tags: ["handmade", "gift", "bestseller"],
        featured: true,
      },
      {
        title: "Nesting Tumbler Set of 4",
        category: "ceramics-tableware",
        price: 1499,
        images: ["cupsStoneware", "mugWhite"],
        summary: "Four handle-less tumblers that stack neatly — for water, buttermilk or a cutting chai.",
        options: [{ name: "Glaze", values: ["Speckled Oat", "Sea Salt"] }],
        specs: [["Capacity", "240 ml each"], ["Material", "Speckled stoneware"], ["Care", "Dishwasher safe"], ["Set", "4 tumblers"]],
        tags: ["handmade", "set"],
      },
      {
        title: "Reactive Glaze Dinner Plates",
        category: "ceramics-tableware",
        price: 2799,
        compareAt: 3499,
        images: ["platesBlue", "kitchen"],
        summary: "A set of four 26 cm plates in a pooling reactive glaze — every set fires a little differently.",
        options: [{ name: "Color", values: ["Tide Blue", "Ash"] }],
        specs: [["Diameter", "26 cm"], ["Set", "4 plates"], ["Material", "Stoneware, reactive glaze"], ["Care", "Dishwasher safe"]],
        tags: ["handmade", "sale"],
        featured: true,
      },
      {
        title: "Sculpted Bud Vase Trio",
        category: "decor",
        price: 1899,
        images: ["vases", "livingRoom"],
        summary: "Three softly faceted bud vases in graduated heights, made for single stems of rajnigandha or dried grasses.",
        options: [{ name: "Finish", values: ["Raw Clay", "Matte White"] }],
        specs: [["Heights", "10 cm, 14 cm, 18 cm"], ["Material", "Stoneware"], ["Watertight", "Yes, glazed interior"]],
        tags: ["handmade", "gift"],
      },
      {
        title: "Sandalwood & Vetiver Soy Candle",
        category: "candles-fragrance",
        price: 749,
        images: ["candleFur1", "candleFur2"],
        summary: "Mysore sandalwood and earthy khus (vetiver) with a hint of vanilla, poured into a reusable stoneware vessel.",
        options: [{ name: "Size", values: ["200 g", "400 g"] }],
        priceMods: { "Size:400 g": 450 },
        specs: [["Burn time", "40 hrs (200 g) / 75 hrs (400 g)"], ["Wax", "Soy blend"], ["Wick", "Cotton"], ["Vessel", "Reusable stoneware"]],
        tags: ["candle", "gift", "bestseller"],
        featured: true,
      },
      {
        title: "Mogra, Champa & Chai Candle Trio",
        category: "candles-fragrance",
        price: 1299,
        images: ["candlesAmber", "candleFur2"],
        summary: "Three 100 g amber-glass candles: jasmine-bright Mogra, sweet Champa and a warm Masala Chai.",
        specs: [["Burn time", "22 hrs each"], ["Wax", "Soy blend"], ["Set", "3 × 100 g"]],
        tags: ["candle", "set", "gift"],
      },
    ],
  },
  {
    slug: "sheesham-house",
    name: "Sheesham House",
    tagline: "Solid-wood furniture and lighting, made in Jodhpur.",
    description:
      "Sheesham House designs furniture that’s easy to live with — honest sheesham and mango wood, clean lines and upholstery you can actually sit on. We work with a network of family-run workshops in Jodhpur and deliver large pieces with free installation in 40+ cities.",
    owner: { name: "Arjun Rathore", email: "arjun@sheeshamhouse.example", avatar: "m1" },
    category: "furniture-lighting",
    location: "Jodhpur, Rajasthan",
    brandColor: "#2b5a8a",
    banner: "livingRoom",
    logo: "chairWhite",
    featured: true,
    verified: true,
    policies: {
      processingTime: "Made to order: 1–3 weeks",
      shipping: "Lighting and small pieces ship via Delhivery. Sofas and chairs are delivered by our own team with free assembly in metro cities.",
      returns: "7-day returns on lighting and decor. Upholstered pieces can be returned within 3 days of delivery (a ₹1,500 pickup fee applies).",
    },
    products: [
      {
        title: "Jodhpur Velvet Sofa",
        category: "seating",
        price: 64999,
        compareAt: 74999,
        images: ["sofaGreen", "livingRoom", "loungeOrange"],
        summary: "A low, deep three-seater in performance velvet on a seasoned sheesham frame.",
        options: [{ name: "Color", values: ["Forest", "Oat"] }],
        specs: [["Dimensions", "213 cm W × 91 cm D × 79 cm H"], ["Seat height", "46 cm"], ["Frame", "Seasoned sheesham wood"], ["Fabric", "Performance velvet"]],
        tags: ["statement", "sale"],
        featured: true,
      },
      {
        title: "Nook Accent Chair",
        category: "seating",
        price: 18499,
        images: ["roomYellowChair", "chairSpot"],
        summary: "A compact lounge chair with a sculpted back and solid wood legs — sized for city apartments.",
        options: [{ name: "Color", values: ["Mustard", "Moss"] }],
        specs: [["Dimensions", "71 cm W × 76 cm D × 81 cm H"], ["Legs", "Solid mango wood"], ["Weight capacity", "135 kg"]],
      },
      {
        title: "Tufted Parlour Chair",
        category: "seating",
        price: 14999,
        images: ["chairWhite"],
        summary: "Button-tufted bouclé on a turned-leg frame. A little drama for a bedroom corner.",
        specs: [["Dimensions", "66 cm W × 71 cm D × 91 cm H"], ["Fabric", "Bouclé"], ["Legs", "Lacquered teak"]],
      },
      {
        title: "Molded Shell Dining Chair",
        category: "seating",
        price: 5499,
        images: ["chairBlack", "diningNook"],
        summary: "A molded shell on a wood-and-steel base. Light, sturdy and easy to keep clean.",
        options: [{ name: "Color", values: ["Black", "White"] }],
        specs: [["Seat height", "45 cm"], ["Shell", "Recycled polypropylene"], ["Base", "Beech & powder-coated steel"]],
        tags: ["bestseller"],
      },
      {
        title: "Sheesham Wood Counter Stool",
        category: "seating",
        price: 4299,
        images: ["stoolWood"],
        summary: "A simple three-legged stool in solid sheesham with a scooped seat and oil finish.",
        options: [{ name: "Height", values: ["Counter 61 cm", "Bar 76 cm"] }],
        priceMods: { "Height:Bar 76 cm": 600 },
        specs: [["Material", "Solid sheesham"], ["Finish", "Hardwax oil"]],
      },
      {
        title: "Wire-Base Bar Stool",
        category: "seating",
        price: 6499,
        images: ["eamesStool"],
        summary: "A classic molded seat on a chromed wire base with footrest.",
        specs: [["Seat height", "76 cm"], ["Base", "Chromed steel"]],
      },
      {
        title: "Beam Floor Lamp",
        category: "lighting",
        price: 4499,
        images: ["lampGrey", "officeLounge"],
        summary: "An articulating floor lamp with a weighted base and a warm LED — made for reading corners.",
        options: [{ name: "Finish", values: ["Graphite", "Bone"] }],
        specs: [["Height", "Adjustable 120–160 cm"], ["Bulb", "Integrated LED, 2700K"], ["Cord", "2.4 m fabric-wrapped, 5A plug"]],
      },
      {
        title: "Harbour Pendant Light",
        category: "lighting",
        price: 3999,
        images: ["pendantTeal"],
        summary: "A spun-aluminium dome pendant with a matte enamel finish. Hang one or a row of three.",
        options: [{ name: "Color", values: ["Teal", "Charcoal", "Cream"] }],
        specs: [["Diameter", "35 cm"], ["Drop", "Adjustable up to 180 cm"], ["Bulb", "B22, up to 60W"]],
        tags: ["bestseller"],
      },
      {
        title: "Copper Dome Pendant Set",
        category: "lighting",
        price: 8999,
        images: ["copperPendants"],
        summary: "Three hand-beaten copper domes from Moradabad on a single canopy — made for over a dining table.",
        specs: [["Shade", "Brushed copper, 25 cm each"], ["Canopy", "Linear, 90 cm"], ["Bulbs", "3 × B22"]],
        featured: true,
      },
      {
        title: "Minimal Wall Clock",
        category: "decor",
        price: 1799,
        images: ["wallClock"],
        summary: "A silent-sweep wall clock with a birch face and slim brass hands.",
        specs: [["Diameter", "30 cm"], ["Movement", "Silent quartz"], ["Face", "Birch ply"]],
      },
      {
        title: "Chunky Knit Throw",
        category: "decor",
        price: 2999,
        images: ["throws"],
        summary: "A heavy hand-knit throw in soft recycled cotton, knitted by a women’s collective in Panipat.",
        options: [{ name: "Color", values: ["Cream", "Sand", "Stone"] }],
        specs: [["Size", "127 × 152 cm"], ["Material", "Recycled cotton"], ["Care", "Cold wash, dry flat"]],
      },
    ],
  },
  {
    slug: "khadi-and-co",
    name: "Khadi & Co.",
    tagline: "Everyday essentials in khadi, linen and organic cotton.",
    description:
      "Khadi & Co. makes the clothes you end up wearing every week: heavyweight tees, honest denim and layers that age well. We work with handloom clusters in Andhra Pradesh and West Bengal, use GOTS-certified organic cotton and produce in small runs to avoid dead stock.",
    owner: { name: "Meera Nair", email: "meera@khadiandco.example", avatar: "w2" },
    category: "fashion",
    location: "Bengaluru, Karnataka",
    brandColor: "#1c1814",
    banner: "boutiqueRacks",
    logo: "rackNeutral",
    featured: true,
    verified: true,
    policies: {
      processingTime: "Ships in 1–2 working days",
      shipping: "Free shipping on orders above ₹1,499. Orders ship plastic-free via Delhivery.",
      returns: "Free returns and size exchanges within 15 days on unworn items with tags attached.",
    },
    products: [
      {
        title: "Organic Cotton Crew Tee",
        category: "tops",
        price: 999,
        images: ["teeWhite", "manTee", "teeBlack"],
        summary: "A 220 GSM organic cotton tee with a clean crew neck and a slightly boxy fit — breathable through a Chennai summer.",
        options: [{ name: "Color", values: ["White", "Black"] }, { name: "Size", values: SIZES_APPAREL }],
        specs: [["Fabric", "100% organic cotton, 220 GSM"], ["Fit", "Relaxed, true to size"], ["Made in", "Tiruppur, Tamil Nadu"]],
        tags: ["essentials", "bestseller"],
        featured: true,
      },
      {
        title: "Heavyweight Pocket Tee",
        category: "tops",
        price: 1299,
        images: ["teeBlack", "manTee"],
        summary: "Our heaviest jersey with a chest pocket and a dropped shoulder.",
        options: [{ name: "Size", values: SIZES_APPAREL }],
        specs: [["Fabric", "100% organic cotton, 280 GSM"], ["Fit", "Oversized"]],
      },
      {
        title: "Heritage Leather Jacket",
        category: "outerwear",
        price: 12999,
        compareAt: 15999,
        images: ["leatherJacket"],
        summary: "A vegetable-tanned lambskin rider jacket that softens and patinas with wear — for Delhi winters and Bengaluru evenings.",
        options: [{ name: "Size", values: ["S", "M", "L", "XL"] }],
        specs: [["Shell", "Vegetable-tanned lambskin"], ["Lining", "Cupro"], ["Hardware", "YKK brass"]],
        tags: ["sale", "statement"],
        featured: true,
      },
      {
        title: "Rust Bomber Jacket",
        category: "outerwear",
        price: 4999,
        images: ["bomberRust"],
        summary: "A lightweight bomber in water-resistant recycled nylon with ribbed trims — monsoon-ready.",
        options: [{ name: "Size", values: SIZES_APPAREL }],
        specs: [["Shell", "Recycled nylon"], ["Water resistance", "DWR finish"]],
      },
      {
        title: "Handwoven Fringe Poncho",
        category: "knitwear-lounge",
        price: 3499,
        images: ["knitPoncho"],
        summary: "An open-weave cotton poncho with hand-tied fringe, woven on handlooms in Kutch.",
        options: [{ name: "Size", values: ["S/M", "M/L"] }],
        specs: [["Fibre", "100% handloom cotton"], ["Care", "Hand wash cold"]],
      },
      {
        title: "Relaxed Linen Shirt",
        category: "tops",
        price: 2799,
        images: ["shirtsSage"],
        summary: "Garment-dyed linen with a camp collar. Gets softer with every wash.",
        options: [{ name: "Color", values: ["Sage", "Olive"] }, { name: "Size", values: SIZES_APPAREL }],
        specs: [["Fabric", "100% linen"], ["Fit", "Relaxed"]],
      },
      {
        title: "Selvedge Straight Jeans",
        category: "bottoms",
        price: 3999,
        images: ["jeans"],
        summary: "13.5 oz selvedge denim in a straight, mid-rise cut, milled in Ahmedabad.",
        options: [{ name: "Waist", values: ["28", "30", "32", "34", "36"] }],
        specs: [["Denim", "13.5 oz selvedge"], ["Rise", "Mid"], ["Inseam", "81 cm"]],
        tags: ["essentials"],
      },
      {
        title: "Tapered Cotton Chinos",
        category: "bottoms",
        price: 2499,
        images: ["chinos"],
        summary: "Soft brushed twill with a little stretch and a tapered leg.",
        options: [{ name: "Waist", values: ["28", "30", "32", "34", "36"] }],
        specs: [["Fabric", "98% cotton, 2% elastane"], ["Fit", "Tapered"]],
      },
      {
        title: "Ribbed Merino Beanie",
        category: "knitwear-lounge",
        price: 1199,
        images: ["knitFlatlay"],
        summary: "A deep-cuff beanie in extra-fine merino. Warm without the itch — ideal for a Manali trip.",
        options: [{ name: "Color", values: ["Rust", "Oat", "Charcoal"] }],
        specs: [["Fibre", "100% extra-fine merino"], ["Size", "One size"]],
      },
      {
        title: "Khadi Cotton Lounge Set",
        category: "knitwear-lounge",
        price: 3299,
        images: ["yellowSet"],
        summary: "A soft khadi-cotton top and jogger set in a confident marigold.",
        options: [{ name: "Size", values: ["XS", "S", "M", "L"] }],
        specs: [["Fabric", "Handspun khadi cotton"], ["Set", "Top + jogger"]],
      },
    ],
  },
  {
    slug: "sole-street",
    name: "Sole Street",
    tagline: "Curated sneakers and everyday shoes from Mumbai.",
    description:
      "Sole Street started as a sneaker swap in Bandra and grew into a curated footwear store. We carry our own label alongside hard-to-find colourways, and every pair ships in its original box.",
    owner: { name: "Kabir Shah", email: "kabir@solestreet.example", avatar: "m2" },
    category: "footwear",
    location: "Mumbai, Maharashtra",
    brandColor: "#7b5ea7",
    banner: "shoppingBag",
    logo: "sneakerPastel",
    verified: true,
    policies: {
      processingTime: "Ships same or next working day",
      shipping: "Free shipping on all orders above ₹1,999. Every pair is double-boxed.",
      returns: "Returns accepted within 10 days on unworn pairs in the original box. Size exchanges are always free.",
    },
    products: [
      {
        title: "Aero Knit Runner",
        category: "sneakers",
        price: 5499,
        images: ["sneakerGrey"],
        summary: "A breathable engineered-knit runner with a responsive foam midsole — built for Marine Drive mornings.",
        options: [{ name: "Size", values: SIZES_SHOES }],
        specs: [["Upper", "Engineered knit"], ["Midsole", "EVA foam"], ["Drop", "8 mm"]],
        tags: ["running", "bestseller"],
        featured: true,
      },
      {
        title: "Court Classic Low",
        category: "sneakers",
        price: 4999,
        images: ["sneakerWhiteOrange"],
        summary: "A leather court shoe with a padded collar and a grippy cupsole.",
        options: [{ name: "Size", values: SIZES_SHOES }],
        specs: [["Upper", "Full-grain leather"], ["Sole", "Rubber cupsole"]],
      },
      {
        title: "Canvas Skate Low",
        category: "sneakers",
        price: 2499,
        images: ["sneakerMaroon"],
        summary: "Heavy canvas, a waffle sole and a padded collar. Built to be beaten up.",
        options: [{ name: "Size", values: SIZES_SHOES }],
        specs: [["Upper", "12 oz canvas"], ["Sole", "Vulcanised waffle rubber"]],
      },
      {
        title: "Volt Trainer",
        category: "sneakers",
        price: 5999,
        images: ["sneakerVolt"],
        summary: "A stable, low-to-the-ground trainer for lifting and HIIT, in high-vis volt.",
        options: [{ name: "Size", values: SIZES_SHOES }],
        specs: [["Upper", "Mesh with TPU cage"], ["Use", "Training"]],
        tags: ["training"],
      },
      {
        title: "Pastel Retro Runner",
        category: "sneakers",
        price: 4799,
        compareAt: 5999,
        images: ["sneakerPastel"],
        summary: "A 90s-inspired runner in soft pastel suede and mesh panels.",
        options: [{ name: "Size", values: SIZES_SHOES }],
        specs: [["Upper", "Suede & mesh"], ["Midsole", "Dual-density foam"]],
        tags: ["sale"],
        featured: true,
      },
      {
        title: "Emerald Suede Loafer",
        category: "casual-shoes",
        price: 6499,
        images: ["shoeGreen"],
        summary: "A soft, unstructured suede loafer handmade in Agra, with a leather-wrapped heel.",
        options: [{ name: "Size", values: SIZES_SHOES }],
        specs: [["Upper", "Suede"], ["Sole", "Leather with rubber heel"], ["Made in", "Agra, Uttar Pradesh"]],
      },
    ],
  },
  {
    slug: "dhvani-audio",
    name: "Dhvani Audio",
    tagline: "Tuned-by-ear audio and considered desk gear from Bengaluru.",
    description:
      "Dhvani (ध्वनि — “sound”) is a small team of audio engineers in Bengaluru. We tune every headphone by ear against studio monitors, and curate a short list of desk and camera gear we use ourselves. Every product carries a two-year warranty with service across India.",
    owner: { name: "Rohit Kulkarni", email: "rohit@dhvaniaudio.example", avatar: "m3" },
    category: "tech",
    location: "Bengaluru, Karnataka",
    brandColor: "#1c1814",
    banner: "laptopDesk",
    logo: "headphonesBeige",
    featured: true,
    verified: true,
    policies: {
      processingTime: "Ships in 1 working day",
      shipping: "Free express delivery on orders above ₹4,999. All electronics ship insured with Blue Dart.",
      returns: "7-day replacement for any defect. Two-year limited warranty on all Dhvani-branded products, with a GST invoice for business purchases.",
    },
    products: [
      {
        title: "Studio One Wireless Headphones",
        category: "audio",
        price: 14999,
        compareAt: 17999,
        images: ["headphonesYellow", "headphonesBeige", "headphonesGrey"],
        summary: "Balanced, warm tuning with 40-hour battery life and plush memory-foam cups.",
        options: [{ name: "Color", values: ["Midnight", "Sand"] }],
        specs: [["Battery", "40 hours"], ["Drivers", "40 mm dynamic"], ["Connectivity", "Bluetooth 5.3, USB-C audio"], ["Weight", "262 g"]],
        tags: ["bestseller", "sale"],
        featured: true,
      },
      {
        title: "Aura ANC Headphones",
        category: "audio",
        price: 21999,
        images: ["headphonesBeige", "headphonesChrome"],
        summary: "Adaptive noise cancelling that shuts out the metro commute without flattening the sound. Folds flat for travel.",
        options: [{ name: "Color", values: ["Sand", "Graphite"] }],
        specs: [["Battery", "30 hours (ANC on)"], ["ANC", "Adaptive hybrid"], ["Connectivity", "Bluetooth 5.3, multipoint"]],
        featured: true,
      },
      {
        title: "Monitor Pro Wired Headphones",
        category: "audio",
        price: 9999,
        images: ["headphonesGrey", "headphonesChrome"],
        summary: "Closed-back studio monitors with a flat response and a detachable cable.",
        specs: [["Type", "Closed-back"], ["Impedance", "38Ω"], ["Cable", "Detachable 3 m coiled"]],
      },
      {
        title: "Pocket Buds Pro",
        category: "audio",
        price: 7999,
        images: ["earbuds"],
        summary: "Tiny, secure-fit earbuds with ANC and a wireless-charging case.",
        options: [{ name: "Color", values: ["Stone", "Black"] }],
        specs: [["Battery", "8 hrs + 24 hrs case"], ["Water resistance", "IPX4"]],
        tags: ["bestseller"],
      },
      {
        title: "Boom Go Portable Speaker",
        category: "audio",
        price: 6499,
        images: ["speakerBlack"],
        summary: "A rugged, waterproof speaker with surprisingly deep bass and 20-hour battery — Goa-beach approved.",
        specs: [["Battery", "20 hours"], ["Water resistance", "IP67"], ["Pairing", "Stereo pair capable"]],
      },
      {
        title: "Pulse Smartwatch",
        category: "wearables",
        price: 16999,
        images: ["smartwatch"],
        summary: "Heart-rate, sleep and workout tracking with a bright always-on display.",
        options: [{ name: "Case", values: ["41 mm", "45 mm"] }],
        priceMods: { "Case:45 mm": 2000 },
        specs: [["Display", "Always-on AMOLED"], ["Battery", "Up to 36 hours"], ["Water resistance", "5 ATM"]],
      },
      {
        title: "Minimal Analog Watch",
        category: "wearables",
        price: 8999,
        images: ["watchWhite"],
        summary: "A 38 mm white-dial watch on a soft silicone strap. Quiet, clean, timeless.",
        specs: [["Case", "38 mm stainless steel"], ["Movement", "Japanese quartz"], ["Strap", "Silicone, quick-release"]],
      },
      {
        title: "Low-Profile Mechanical Keyboard",
        category: "desk-setup",
        price: 8499,
        images: ["keyboardMech", "laptopDesk"],
        summary: "A 75% aluminium keyboard with hot-swap switches and tri-mode connectivity.",
        options: [{ name: "Switch", values: ["Brown (tactile)", "Red (linear)"] }],
        specs: [["Layout", "75%, ANSI"], ["Case", "CNC aluminium"], ["Connectivity", "USB-C, Bluetooth, 2.4 GHz"]],
        tags: ["bestseller"],
      },
      {
        title: "Slim Wireless Keyboard",
        category: "desk-setup",
        price: 4999,
        images: ["keyboardWhite"],
        summary: "A quiet, full-size scissor-switch keyboard that pairs with three devices.",
        specs: [["Layout", "Full size"], ["Battery", "3 months per charge"]],
      },
      {
        title: "Silent Wireless Mouse",
        category: "desk-setup",
        price: 2499,
        images: ["mouseWhite"],
        summary: "Near-silent clicks and a sculpted shape that fits most hands.",
        options: [{ name: "Color", values: ["Cream", "Graphite"] }],
        specs: [["Sensor", "4000 DPI optical"], ["Battery", "70 days"]],
      },
      {
        title: "Retro Instant Camera",
        category: "cameras",
        price: 8999,
        images: ["instantCamera"],
        summary: "Point, shoot and hold a print in your hand in 90 seconds — the wedding-sangeet favourite.",
        specs: [["Film", "Instant i-Type / 600"], ["Flash", "Built-in"], ["Power", "USB-C rechargeable"]],
      },
      {
        title: "Mirrorless Starter Kit",
        category: "cameras",
        price: 54999,
        compareAt: 62999,
        images: ["cameraCanon", "cameraDark"],
        summary: "A 24 MP APS-C body with a 15–45 mm kit lens, spare battery and strap.",
        specs: [["Sensor", "24.2 MP APS-C"], ["Video", "4K 30p"], ["Kit", "Body, 15–45 mm lens, 2 batteries"]],
        tags: ["sale"],
      },
      {
        title: "Wireless Game Controller",
        category: "desk-setup",
        price: 3999,
        images: ["controller"],
        summary: "Hall-effect sticks, textured grips and 40-hour battery life.",
        specs: [["Compatibility", "PC, Android, iOS"], ["Battery", "40 hours"]],
      },
    ],
  },
  {
    slug: "hara-bhara-plants",
    name: "Hara Bhara Plants",
    tagline: "Healthy houseplants from our Pune nursery, delivered with care.",
    description:
      "Hara Bhara is a nursery-to-door plant shop in Pune. We grow most of our plants ourselves, pot them in breathable ceramic and terracotta, and ship in custom packaging that keeps them snug in transit. Every plant comes with a care card and our 15-day happy-plant guarantee.",
    owner: { name: "Sneha Deshpande", email: "sneha@harabhara.example", avatar: "w4" },
    category: "plants-outdoor",
    location: "Pune, Maharashtra",
    brandColor: "#2f6f4f",
    banner: "greenRoom",
    logo: "succulentTeal",
    verified: true,
    policies: {
      processingTime: "Ships Monday–Wednesday so plants don’t sit in transit over Sunday",
      shipping: "Plants ship in ventilated boxes. Flat ₹99 shipping, free above ₹799. Same-day delivery within Pune.",
      returns: "15-day happy-plant guarantee: if your plant arrives unhealthy or struggles in the first two weeks, we’ll replace it.",
    },
    products: [
      {
        title: "Monstera Deliciosa",
        category: "houseplants",
        price: 1299,
        images: ["monstera"],
        summary: "The classic split-leaf plant, well-rooted and ready to climb a moss pole.",
        options: [{ name: "Size", values: ["Medium (15 cm pot)", "Large (25 cm pot)"] }],
        priceMods: { "Size:Large (25 cm pot)": 1200 },
        specs: [["Light", "Bright, indirect"], ["Water", "Every 7–10 days"], ["Pet friendly", "No"]],
        tags: ["bestseller"],
        featured: true,
      },
      {
        title: "Aloe Vera in Ceramic Pot",
        category: "houseplants",
        price: 599,
        images: ["aloe"],
        summary: "A hardy, sculptural aloe — ghritkumari — in a white ceramic pot with drainage.",
        specs: [["Light", "Bright, direct"], ["Water", "Every 2–3 weeks"], ["Pot", "12 cm ceramic"]],
      },
      {
        title: "Echeveria in Teal Planter",
        category: "houseplants",
        price: 449,
        images: ["succulentTeal"],
        summary: "A rosette succulent in a glossy teal planter — nearly impossible to kill.",
        specs: [["Light", "Bright"], ["Water", "Every 2–3 weeks"], ["Pet friendly", "Yes"]],
        tags: ["gift"],
      },
      {
        title: "Mini Cactus in Terracotta Pot",
        category: "houseplants",
        price: 349,
        images: ["cactusPink"],
        summary: "A small columnar cactus in a terracotta pot, perfect for a sunny windowsill.",
        specs: [["Light", "Full sun"], ["Water", "Monthly"], ["Pot", "9 cm terracotta"]],
        tags: ["gift"],
      },
      {
        title: "Money Plant Cutting Kit",
        category: "houseplants",
        price: 299,
        images: ["plantSprig"],
        summary: "Three rooted golden money plant (pothos) cuttings, a glass propagation jar and a care guide.",
        specs: [["Includes", "3 cuttings, glass jar"], ["Light", "Low to bright indirect"]],
      },
      {
        title: "Desert Cactus Collection",
        category: "houseplants",
        price: 999,
        images: ["cactusField"],
        summary: "Five assorted cacti in 10 cm nursery pots, hand-picked from the nursery.",
        specs: [["Includes", "5 plants"], ["Light", "Full sun"]],
      },
      {
        title: "Forged Garden Trowel",
        category: "garden",
        price: 699,
        images: ["trowel"],
        summary: "A forged stainless trowel with a sheesham handle and depth markings.",
        specs: [["Blade", "Forged stainless steel"], ["Handle", "Sheesham wood"], ["Length", "30 cm"]],
      },
    ],
  },
  {
    slug: "kesar-botanicals",
    name: "Kesar Botanicals",
    tagline: "Ayurveda-inspired, fragrance-conscious skincare from Kochi.",
    description:
      "Kesar Botanicals formulates short-ingredient-list skincare rooted in Kerala’s Ayurvedic traditions — kumkumadi, neem, tulsi, kokum — for sensitive skin. Everything is made in small batches, dermatologist tested, cruelty-free and packaged in glass wherever possible.",
    owner: { name: "Lakshmi Menon", email: "lakshmi@kesarbotanicals.example", avatar: "w1" },
    category: "beauty",
    location: "Kochi, Kerala",
    brandColor: "#b3872a",
    banner: "skincareFlatlay",
    logo: "skincareSet",
    featured: true,
    verified: true,
    policies: {
      processingTime: "Ships in 1–2 working days",
      shipping: "Free shipping on orders above ₹699. Cash on delivery available across India.",
      returns: "Unopened products can be returned within 7 days. If a product doesn’t suit your skin, write to us — we’ll help you find one that does.",
    },
    products: [
      {
        title: "Neem & Tulsi Face Wash",
        category: "skincare",
        price: 449,
        images: ["skincareTube", "skincareSet"],
        summary: "A low-foam gel cleanser with neem, tulsi and glycerin that clears without leaving skin tight.",
        options: [{ name: "Size", values: ["100 ml", "200 ml"] }],
        priceMods: { "Size:200 ml": 300 },
        specs: [["Skin type", "All, including oily & sensitive"], ["Key ingredients", "Neem, tulsi, glycerin"], ["Fragrance", "None added"]],
        tags: ["bestseller"],
        featured: true,
      },
      {
        title: "Aloe & Ceramide Night Cream",
        category: "skincare",
        price: 899,
        images: ["creamTube", "creamJar"],
        summary: "A rich ceramide cream with aloe that calms redness and locks in moisture overnight.",
        specs: [["Skin type", "Dry, sensitive"], ["Key ingredients", "Ceramides, aloe vera, squalane"], ["Size", "50 g"]],
      },
      {
        title: "Night Renewal Duo",
        category: "skincare",
        price: 1899,
        images: ["purpleBottles"],
        summary: "A gentle retinal serum paired with a recovery moisturiser.",
        specs: [["Includes", "30 ml serum, 50 g cream"], ["Key ingredients", "Retinal, niacinamide"]],
      },
      {
        title: "Everyday Ritual Set",
        category: "skincare",
        price: 2499,
        compareAt: 2999,
        images: ["skincareSet", "skincareFlatlay"],
        summary: "Face wash, serum and moisturiser — our three bestsellers in one gift box.",
        specs: [["Includes", "Face wash, Vitamin C serum, Night cream"], ["Savings", "17% vs. buying separately"]],
        tags: ["set", "gift", "sale"],
        featured: true,
      },
      {
        title: "Kumkumadi Radiance Face Oil",
        category: "skincare",
        price: 1299,
        images: ["oilDropper", "amberDropper"],
        summary: "A classical Ayurvedic blend of saffron (kesar), manjistha and sandalwood in cold-pressed oils, for a healthy, non-greasy glow.",
        specs: [["Size", "30 ml"], ["Key ingredients", "Saffron, manjistha, sandalwood"]],
      },
      {
        title: "Vitamin C Brightening Serum",
        category: "skincare",
        price: 999,
        images: ["amberDropper", "serumBottles"],
        summary: "A stable 15% vitamin C serum with ferulic acid and amla extract.",
        specs: [["Size", "30 ml"], ["Key ingredients", "15% L-ascorbic acid, ferulic acid, amla"]],
        tags: ["bestseller"],
      },
      {
        title: "Whipped Kokum Body Butter",
        category: "bath-body",
        price: 699,
        images: ["creamJar"],
        summary: "Kokum and shea butter whipped light enough for humid Mumbai days.",
        options: [{ name: "Scent", values: ["Unscented", "Mogra", "Sandalwood"] }],
        specs: [["Size", "200 g"], ["Key ingredients", "Kokum butter, shea butter"]],
      },
      {
        title: "Cold-Process Soap Set",
        category: "bath-body",
        price: 599,
        images: ["soapBars"],
        summary: "Four cold-process bars: neem, haldi-chandan, charcoal and rose.",
        specs: [["Set", "4 × 100 g bars"], ["Process", "Cold-process, cured 6 weeks"]],
        tags: ["gift", "set"],
      },
      {
        title: "Abhyanga Bath Ritual Kit",
        category: "bath-body",
        price: 1799,
        images: ["apothecary"],
        summary: "Warm massage oil, ubtan, a dry brush and bath salts — a slow Sunday in a box.",
        specs: [["Includes", "4 items"], ["Gift wrap", "Included"]],
        tags: ["gift"],
      },
      {
        title: "Pro Makeup Brush Set",
        category: "makeup-tools",
        price: 1499,
        images: ["makeupBrushes"],
        summary: "Eight vegan synthetic brushes with weighted handles and a travel roll.",
        specs: [["Set", "8 brushes + roll"], ["Bristles", "Vegan synthetic"]],
      },
      {
        title: "Refillable Glass Pump Bottles",
        category: "bath-body",
        price: 699,
        images: ["pumpBottles"],
        summary: "Three frosted glass pump bottles for decanting shampoo, handwash and lotion.",
        specs: [["Set", "3 × 300 ml"], ["Material", "Frosted glass, steel pump"]],
      },
    ],
  },
  {
    slug: "tanvi-jewels",
    name: "Tanvi Jewels",
    tagline: "Hallmarked gold and silver jewellery, hand-finished in Jaipur.",
    description:
      "Tanvi Jewels is a third-generation jewellery workshop in Jaipur’s Johari Bazaar, working in BIS-hallmarked 14k gold, 925 sterling silver and ethically sourced stones. Every piece is cast, set and polished by our karigars, and ships with a certificate of authenticity.",
    owner: { name: "Tanvi Agarwal", email: "tanvi@tanvijewels.example", avatar: "w5" },
    category: "jewelry",
    location: "Jaipur, Rajasthan",
    brandColor: "#b3872a",
    banner: "craftTools",
    logo: "goldRings",
    verified: true,
    policies: {
      processingTime: "Ready pieces ship in 2 days; custom sizes in 10–15 days",
      shipping: "Free insured shipping on every order via Blue Dart. Signature required above ₹25,000.",
      returns: "Returns within 7 days in original condition. Custom-sized rings are final sale but can be resized once for free.",
    },
    products: [
      {
        title: "Hyderabadi Pearl Strand",
        category: "necklaces",
        price: 6999,
        images: ["pearls"],
        summary: "A single strand of hand-knotted 7 mm pearls, sourced from the pearl merchants of Hyderabad’s Charminar.",
        options: [{ name: "Length", values: ["40 cm", "45 cm"] }],
        specs: [["Pearls", "7 mm freshwater"], ["Clasp", "Gold-plated silver"]],
        featured: true,
      },
      {
        title: "Sapphire Drop Pendant",
        category: "necklaces",
        price: 8499,
        images: ["pendantNecklace", "necklaceModel"],
        summary: "A lab-grown sapphire in a hand-cut bezel on a fine cable chain.",
        specs: [["Metal", "14k gold, BIS hallmarked"], ["Stone", "Lab-grown sapphire, 0.5 ct"], ["Chain", "45 cm cable"]],
      },
      {
        title: "Halo Solitaire Ring",
        category: "rings",
        price: 89999,
        images: ["ringDiamond"],
        summary: "A round lab-grown diamond in a pavé halo on a split-shank band.",
        options: [{ name: "Size", values: ["10", "12", "14", "16"] }],
        specs: [["Metal", "18k white gold, BIS hallmarked"], ["Centre", "Lab-grown diamond, 1 ct"], ["Certification", "IGI"]],
        tags: ["statement"],
      },
      {
        title: "Rose Gold Link Bracelet",
        category: "earrings-bracelets",
        price: 5499,
        images: ["braceletRose"],
        summary: "A delicate pavé link bracelet in rose gold vermeil.",
        specs: [["Metal", "Rose gold vermeil on 925 silver"], ["Length", "17 cm with extender"]],
        tags: ["gift"],
      },
      {
        title: "Blue Topaz Drop Earrings",
        category: "earrings-bracelets",
        price: 7499,
        images: ["earringsBlue"],
        summary: "London blue topaz in a vintage-inspired halo drop, set in Jaipur.",
        specs: [["Metal", "925 sterling silver"], ["Stone", "London blue topaz"]],
      },
      {
        title: "Stacking Ring Set",
        category: "rings",
        price: 2999,
        images: ["goldRings"],
        summary: "Three textured stacking bands — one hammered, one twisted, one smooth.",
        options: [{ name: "Size", values: ["10", "12", "14", "16"] }],
        specs: [["Metal", "Gold-plated 925 silver"], ["Set", "3 rings"]],
        tags: ["bestseller"],
      },
      {
        title: "Layered Chain Necklace",
        category: "necklaces",
        price: 2499,
        images: ["necklaceModel"],
        summary: "Two fine chains on a single clasp — the layered look, without the tangles.",
        specs: [["Metal", "Gold vermeil"], ["Lengths", "40 cm and 45 cm"]],
      },
      {
        title: "Classic Wayfarer Sunglasses",
        category: "eyewear",
        price: 3999,
        images: ["sunglasses"],
        summary: "Hand-polished acetate frames with polarised, UV400 lenses.",
        specs: [["Frame", "Acetate"], ["Lens", "Polarised, UV400"]],
      },
    ],
  },
  {
    slug: "chamda-leather-works",
    name: "Chamda Leather Works",
    tagline: "Leather bags and handmade paper goods for the daily carry.",
    description:
      "Chamda Leather Works makes bags that get better with use — full-grain leather from Kanpur’s tanneries, waxed canvas and solid brass hardware, cut and stitched in our Kanpur workshop. We also stock handmade paper from Sanganer for the things you carry in them.",
    owner: { name: "Imran Siddiqui", email: "imran@chamda.example", avatar: "m4" },
    category: "bags-accessories",
    location: "Kanpur, Uttar Pradesh",
    brandColor: "#a8461f",
    banner: "storeInterior",
    logo: "handbagWoven",
    featured: true,
    policies: {
      processingTime: "Ships in 2–3 working days",
      shipping: "Free shipping above ₹1,499. Monogramming adds 2 days.",
      returns: "10-day returns on unused, un-monogrammed items. Free repairs on all leather goods for life.",
    },
    products: [
      {
        title: "Structured Top-Handle Bag",
        category: "handbags",
        price: 7999,
        images: ["handbagRed"],
        summary: "A compact, structured bag in glossy full-grain leather with a detachable strap.",
        options: [{ name: "Color", values: ["Cherry", "Black"] }],
        specs: [["Leather", "Full-grain calf leather"], ["Dimensions", "23 × 18 × 10 cm"], ["Hardware", "Solid brass"]],
        featured: true,
      },
      {
        title: "Woven Leather Basket Bag",
        category: "handbags",
        price: 5999,
        images: ["handbagWoven"],
        summary: "Hand-woven leather in a basket weave with a structured frame.",
        specs: [["Leather", "Vegetable-tanned"], ["Dimensions", "25 × 20 × 13 cm"]],
      },
      {
        title: "Teal Leather Satchel",
        category: "handbags",
        price: 6999,
        images: ["handbagTeal"],
        summary: "A roomy satchel in deep teal pebbled leather with a crossbody strap.",
        specs: [["Leather", "Pebbled cowhide"], ["Fits", "13-inch tablet"]],
      },
      {
        title: "Everyday Commuter Backpack",
        category: "backpacks",
        price: 3999,
        images: ["backpackNavy"],
        summary: "A clean 20 L pack with a padded laptop sleeve and a water-resistant shell — monsoon-proof for the daily commute.",
        options: [{ name: "Color", values: ["Navy", "Black"] }],
        specs: [["Volume", "20 L"], ["Laptop", "Up to 16 inch"], ["Shell", "Recycled nylon, DWR"]],
        tags: ["bestseller"],
        featured: true,
      },
      {
        title: "Canvas Rolltop Backpack",
        category: "backpacks",
        price: 2999,
        images: ["backpackRed"],
        summary: "A waxed canvas rolltop that expands from 18 L to 24 L.",
        specs: [["Volume", "18–24 L"], ["Material", "Waxed canvas, leather trim"]],
      },
      {
        title: "Bifold Leather Wallet",
        category: "small-leather-goods",
        price: 1499,
        images: ["wallet"],
        summary: "A slim bifold with six card slots and a note pocket, edge-painted by hand.",
        options: [{ name: "Color", values: ["Tan", "Espresso"] }],
        specs: [["Leather", "Full-grain buffalo leather"], ["Slots", "6 cards + notes"]],
        tags: ["gift"],
      },
      {
        title: "Washable Kraft Paper Tote",
        category: "small-leather-goods",
        price: 799,
        images: ["toteKraft"],
        summary: "Washable kraft paper that feels like leather and weighs almost nothing.",
        specs: [["Material", "Washable kraft paper"], ["Dimensions", "35 × 40 cm"]],
      },
      {
        title: "Sanganer Handmade Paper Notebook & Pen",
        category: "stationery",
        price: 699,
        images: ["notebookPen", "penBlack"],
        summary: "A lay-flat A5 notebook of cotton-rag handmade paper from Sanganer, with a matching rollerball.",
        specs: [["Paper", "120 GSM handmade cotton-rag, dot grid"], ["Pages", "192"], ["Binding", "Lay-flat"]],
      },
      {
        title: "Weighted Brass Pen",
        category: "stationery",
        price: 1299,
        images: ["penBlack"],
        summary: "A machined pen with a satisfying weight and a smooth gel refill.",
        specs: [["Body", "Anodised aluminium with brass core"], ["Refill", "0.5 mm gel"]],
      },
    ],
  },
  {
    slug: "baba-budan-roasters",
    name: "Baba Budan Roasters",
    tagline: "Estate coffee, roasted every Tuesday in Chikkamagaluru.",
    description:
      "We buy coffee directly from a handful of estates in the Baba Budan hills — where coffee first came to India — roast it in small batches every Tuesday and ship it the same day. Coffee that’s never more than a week off the roaster when it reaches your filter.",
    owner: { name: "Karthik Gowda", email: "karthik@bababudan.example", avatar: "m1" },
    category: "coffee-kitchen",
    location: "Chikkamagaluru, Karnataka",
    brandColor: "#7a3013",
    banner: "shopCounter",
    logo: "coffeeBeans",
    verified: true,
    policies: {
      processingTime: "Roasted Tuesday, shipped Tuesday",
      shipping: "Flat ₹49 shipping, free on orders above ₹599.",
      returns: "If you don’t love a coffee, tell us and we’ll send a different one free.",
    },
    products: [
      {
        title: "Chikmagalur Estate Arabica",
        category: "coffee-tea",
        price: 549,
        images: ["coffeeBag", "coffeeBeans"],
        summary: "A shade-grown single-estate arabica with notes of jaggery, orange and cocoa.",
        options: [{ name: "Grind", values: ["Whole bean", "Espresso", "South Indian filter"] }, { name: "Size", values: ["250 g", "1 kg"] }],
        priceMods: { "Size:1 kg": 1350 },
        specs: [["Roast", "Medium-light"], ["Process", "Washed"], ["Altitude", "1,200–1,500 m"]],
        tags: ["bestseller"],
        featured: true,
      },
      {
        title: "Monsooned Malabar Espresso Blend",
        category: "coffee-tea",
        price: 499,
        images: ["coffeeBeans", "espresso"],
        summary: "Monsooned Malabar and robusta for a heavy, chocolatey body that holds up to milk and sugar.",
        options: [{ name: "Grind", values: ["Whole bean", "Espresso"] }],
        specs: [["Roast", "Medium-dark"], ["Origins", "Malabar coast, Coorg"]],
        tags: ["bestseller"],
      },
      {
        title: "Cold Brew Tonic Kit",
        category: "coffee-tea",
        price: 899,
        images: ["icedTea"],
        summary: "Coarse-ground cold brew coffee, filter bags and a kokum-citrus syrup for tonic.",
        specs: [["Makes", "8 servings"], ["Includes", "Coffee, filters, syrup"]],
      },
      {
        title: "Espresso Cup & Saucer Pair",
        category: "kitchen-tools",
        price: 1199,
        images: ["espresso"],
        summary: "Thick-walled porcelain that holds heat. Two cups, two saucers.",
        specs: [["Capacity", "90 ml"], ["Material", "Porcelain"]],
      },
      {
        title: "Latte Art Starter Kit",
        category: "kitchen-tools",
        price: 1799,
        images: ["latteArt", "lattes"],
        summary: "A 350 ml pitcher, thermometer and etching pen — plus a video lesson.",
        specs: [["Pitcher", "350 ml stainless steel"], ["Includes", "Thermometer, etching pen"]],
      },
      {
        title: "Loose Leaf Masala Chai",
        category: "coffee-tea",
        price: 349,
        images: ["teaCookies"],
        summary: "Assam CTC with whole elaichi, ginger, cinnamon and clove — just add milk and boil.",
        specs: [["Weight", "250 g (about 120 cups)"], ["Caffeine", "Medium"]],
      },
      {
        title: "Damascus Chef Knife Set",
        category: "kitchen-tools",
        price: 12999,
        compareAt: 15999,
        images: ["knives", "kitchen"],
        summary: "Five 67-layer Damascus knives with rosewood handles and a canvas roll.",
        specs: [["Steel", "VG-10 core, 67 layers"], ["Includes", "5 knives + roll"]],
        tags: ["sale", "gift"],
      },
    ],
  },
  {
    slug: "himalayan-trail-co",
    name: "Himalayan Trail Co.",
    tagline: "Trail-tested gear for weekends in the hills.",
    description:
      "Himalayan Trail Co. is run by two former trek leaders in Dehradun. We carry a short list of gear we’ve tested on real trips — Kedarkantha, Hampta Pass, the Valley of Flowers — and nothing we wouldn’t take ourselves.",
    owner: { name: "Aditi Rawat", email: "aditi@himalayantrail.example", avatar: "w2" },
    category: "plants-outdoor",
    location: "Dehradun, Uttarakhand",
    brandColor: "#2f6f4f",
    banner: "campfire",
    logo: "tentView",
    policies: {
      processingTime: "Ships in 1–2 working days",
      shipping: "Free shipping above ₹999 anywhere in India, including the North-East and J&K.",
      returns: "30-day returns, even if you’ve used it on a trek. We want you to test it.",
    },
    products: [
      {
        title: "Ridge 2-Person Tent",
        category: "outdoor-gear",
        price: 14999,
        images: ["tentView", "campfire"],
        summary: "A freestanding three-season tent with two doors and a 1.5 kg trail weight.",
        specs: [["Capacity", "2 people"], ["Trail weight", "1.5 kg"], ["Seasons", "3"]],
        featured: true,
      },
      {
        title: "Insulated Trail Bottle",
        category: "outdoor-gear",
        price: 1299,
        images: ["bottleGreen"],
        summary: "Double-wall vacuum insulation: cold for 24 hours, hot chai for 12.",
        options: [{ name: "Color", values: ["Sage", "Stone"] }, { name: "Size", values: ["600 ml", "1 L"] }],
        priceMods: { "Size:1 L": 300 },
        specs: [["Material", "18/8 stainless steel"], ["Insulation", "Double-wall vacuum"]],
        tags: ["bestseller"],
      },
      {
        title: "Cork Yoga Mat",
        category: "outdoor-gear",
        price: 2999,
        images: ["yoga"],
        summary: "Natural cork on a rubber base — grippier the more you sweat.",
        specs: [["Thickness", "5 mm"], ["Size", "183 × 66 cm"]],
      },
      {
        title: "Campfire Wool Blanket",
        category: "outdoor-gear",
        price: 3499,
        images: ["campfire", "throws"],
        summary: "A dense Himachali wool blanket that shrugs off sparks and damp grass.",
        specs: [["Material", "80% wool, woven in Kullu"], ["Size", "152 × 203 cm"]],
      },
    ],
  },
];

export type CustomerSeed = {
  name: string;
  email: string;
  avatar?: keyof typeof AVATARS;
  /** Local illustrated avatar (overrides `avatar`). */
  image?: string;
  address: { line1: string; line2: string | null; city: string; region: string; postalCode: string; phone: string };
};

export const CUSTOMERS: CustomerSeed[] = [
  { name: "Rishi Chaurasia", email: "customer@vanik.dev", image: "/avatars/rishi.svg", address: { line1: "Flat 402, Prestige Shantiniketan", line2: "Whitefield Main Road", city: "Bengaluru", region: "Karnataka", postalCode: "560048", phone: "+91 98450 12345" } },
  { name: "Rohan Mehta", email: "rohan.mehta@example.com", avatar: "m2", address: { line1: "B-14, Sea Breeze Apartments", line2: "Carter Road, Bandra West", city: "Mumbai", region: "Maharashtra", postalCode: "400050", phone: "+91 98200 45678" } },
  { name: "Priyanka Iyer", email: "priyanka.iyer@example.com", avatar: "w1", address: { line1: "12, 3rd Cross Street", line2: "Besant Nagar", city: "Chennai", region: "Tamil Nadu", postalCode: "600090", phone: "+91 94440 23456" } },
  { name: "Arjun Nair", email: "arjun.nair@example.com", avatar: "m4", address: { line1: "Kochuparambil House", line2: "Panampilly Nagar", city: "Kochi", region: "Kerala", postalCode: "682036", phone: "+91 94470 34567" } },
  { name: "Kavya Reddy", email: "kavya.reddy@example.com", avatar: "w3", address: { line1: "Plot 88, Road No. 12", line2: "Banjara Hills", city: "Hyderabad", region: "Telangana", postalCode: "500034", phone: "+91 98480 56789" } },
  { name: "Vikram Singh", email: "vikram.singh@example.com", avatar: "m3", address: { line1: "C-42, Bapu Nagar", line2: "Near Rajasthan University", city: "Jaipur", region: "Rajasthan", postalCode: "302015", phone: "+91 94140 67890" } },
  { name: "Sneha Kulkarni", email: "sneha.kulkarni@example.com", avatar: "w5", address: { line1: "Flat 7, Shivam Heights", line2: "Kothrud", city: "Pune", region: "Maharashtra", postalCode: "411038", phone: "+91 98220 78901" } },
  { name: "Aditya Verma", email: "aditya.verma@example.com", address: { line1: "3/112, Vikas Khand", line2: "Gomti Nagar", city: "Lucknow", region: "Uttar Pradesh", postalCode: "226010", phone: "+91 94150 89012" } },
  { name: "Meera Joshi", email: "meera.joshi@example.com", avatar: "w2", address: { line1: "21, Sunrise Park Society", line2: "Bodakdev", city: "Ahmedabad", region: "Gujarat", postalCode: "380054", phone: "+91 98250 90123" } },
  { name: "Karan Malhotra", email: "karan.malhotra@example.com", avatar: "m1", address: { line1: "E-47, Second Floor", line2: "Greater Kailash II", city: "New Delhi", region: "Delhi", postalCode: "110048", phone: "+91 98110 01234" } },
  { name: "Ishita Banerjee", email: "ishita.banerjee@example.com", address: { line1: "17B, Lake Place", line2: "Southern Avenue", city: "Kolkata", region: "West Bengal", postalCode: "700029", phone: "+91 98300 11223" } },
  { name: "Siddharth Rao", email: "siddharth.rao@example.com", address: { line1: "No. 9, 2nd Main", line2: "Jayalakshmipuram", city: "Mysuru", region: "Karnataka", postalCode: "570012", phone: "+91 94480 22334" } },
  { name: "Neha Gupta", email: "neha.gupta@example.com", address: { line1: "Tower 3, Flat 1104, DLF Park Place", line2: "Sector 54", city: "Gurugram", region: "Haryana", postalCode: "122002", phone: "+91 98100 33445" } },
  { name: "Rahul Desai", email: "rahul.desai@example.com", address: { line1: "A-601, Green Avenue", line2: "Vesu", city: "Surat", region: "Gujarat", postalCode: "395007", phone: "+91 98790 44556" } },
  { name: "Aisha Khan", email: "aisha.khan@example.com", address: { line1: "House 23, Shyamla Hills", line2: "Near Van Vihar", city: "Bhopal", region: "Madhya Pradesh", postalCode: "462013", phone: "+91 94250 55667" } },
  { name: "Tanvir Ahmed", email: "tanvir.ahmed@example.com", address: { line1: "Flat 2C, Brahmaputra Residency", line2: "Zoo Road, Tiniali", city: "Guwahati", region: "Assam", postalCode: "781024", phone: "+91 94350 66778" } },
];

export const REVIEW_BANK: Record<1 | 2 | 3 | 4 | 5, { title: string; body: string }[]> = {
  5: [
    { title: "Exactly what I hoped for", body: "The quality is obvious the moment you open the box. Packaging was thoughtful and it arrived a day early. Already planning to order another as a gift." },
    { title: "Beautiful and well made", body: "Photos don’t do it justice — the finish and detail are lovely in person. You can tell a real person cared about making this." },
    { title: "Worth every rupee", body: "I hesitated at the price but I’m so glad I went for it. It feels substantial and I use it every single day." },
    { title: "My new favourite", body: "I’ve tried a lot of alternatives and this is the one I keep reaching for. Great communication from the seller too." },
    { title: "Diwali gift was a huge hit", body: "Bought this for my sister and she hasn’t stopped talking about it. Came beautifully wrapped with a handwritten note." },
    { title: "Five stars, no notes", body: "Arrived quickly, looks great, works perfectly. This is how online shopping should feel." },
    { title: "Better than the big brands", body: "Honestly nicer than what I used to buy at the mall, and I love supporting an Indian maker." },
  ],
  4: [
    { title: "Really lovely, minor quibble", body: "Love it overall. Delivery took a couple of days longer than the estimate, but the product itself is great quality." },
    { title: "Great quality", body: "Well made and looks great. Slightly different colour than the photos in my lighting, but I still like it a lot." },
    { title: "Would buy again", body: "Solid purchase. It does exactly what it says. Knocked off a star only because the packaging was a bit excessive." },
    { title: "Very happy", body: "Nice attention to detail and the seller answered my WhatsApp query within an hour. Sizing runs slightly small." },
  ],
  3: [
    { title: "It’s fine", body: "Does the job, but I expected a little more at this price. The finish is nice though." },
    { title: "Mixed feelings", body: "Some things I love about it, some I don’t. Customer service was helpful when I reached out." },
  ],
  2: [
    { title: "Not quite for me", body: "The quality seems okay but it wasn’t what I expected from the photos. The seller offered a return, which I appreciated." },
  ],
  1: [
    { title: "Arrived damaged", body: "Unfortunately mine arrived with a chip — the courier was rough with it. The seller did send a replacement quickly, to be fair." },
  ],
};

export const VENDOR_RESPONSES = [
  "Thank you so much for the kind words — it means a lot to our small team!",
  "We’re so glad it arrived safely. Thank you for supporting Indian makers.",
  "Thanks for the honest feedback. We’ve passed your note along to our packing team.",
  "Sorry this wasn’t perfect! Please reach out anytime — we’ll make it right.",
  "So happy to hear it was a hit as a gift. Thanks for shopping with us!",
];
